# Generated by Django 3.1.6 on 2021-03-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_auto_20210329_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=120),
        ),
    ]
